#SERVER
server:
  port: 8081
  servlet:
    context-path: /api
  compression:
    enabled: true
    min-response-size: 2KB

# DATABASE
spring:
  application:
    name: video_store_exam

  datasource:
    url: jdbc:${DB_VENDOR}://${DB_HOSTNAME}:${DB_PORT}/${DB_NAME}?ssl-mode=REQUIRED
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      dialect: org.hibernate.dialect.MySQLDialect
      hibernate:
        format_sql: true
    show-sql: true
    open-in-view: false
    defer-datasource-initialization: true



# LOGGING
logging:
  level:
    it.cgmconsulting: info
    org:
      springframework:
        boot: info
        security: info
    org.hibernate.orm.jdbc.bind: trace
  file.name: /Users/Public/folino/log/folino_log.txt